CREATE TABLE roles
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  nome VARCHAR(255) UNIQUE NOT NULL,
);
GO

CREATE TABLE privilegios
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  nome VARCHAR(255) UNIQUE NOT NULL
);
GO

CREATE TABLE usuarios_roles
(
  usuario_id UNIQUEIDENTIFIER NOT NULL,
  roles_id UNIQUEIDENTIFIER NOT NULL,
  PRIMARY KEY (usuario_id, roles_id),
  FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
  FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);
GO

CREATE TABLE roles_privilegios
(
  roles_id UNIQUEIDENTIFIER NOT NULL,
  privilegio_id UNIQUEIDENTIFIER NOT NULL,
  PRIMARY KEY (roles_id, privilegio_id),
  FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (privilegio_id) REFERENCES privilegios(id) ON DELETE CASCADE
);
GO

CREATE TYPE ListaDeIds AS TABLE
(
  id UNIQUEIDENTIFIER NOT NULL
);
GO

CREATE TYPE ListaRetorno AS TABLE
(
  id UNIQUEIDENTIFIER NOT NULL,
  nome VARCHAR(255) NOT NULL
);
GO